[package]
name = "roogle"
version = "0.1.0"
authors = ["Joern Bernhardt <joern.bernhardt@googlemail.com>"]
publish = false

[dependencies]
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
web-view = "0.4.0"
