[package]
name = "roogle"
version = "0.1.0"
authors = ["Joern Bernhardt <joern.bernhardt@googlemail.com>"]
publish = false

[dependencies]
base64 = "0.10"
error-chain = "0.12"
reqwest = "0.9"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
url = "1.7"
web-view = "0.4.0"
